[package]
name = "vec_historic"
version = "0.1.0"
edition = "2024"
authors = ["zieklass"]
description = "Rust Undo Collection"
license = "MIT OR Apache-2.0"
categories = ["data-structures"]
readme = "README.md"

[lib]
path = "src/lib.rs"

[dependencies]
gapbuf = "0.1.4"
indexmap = "2.10.0"
